// Package generator creates the builtin/plugins.go blank-import file.
package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nuxtblog/nuxtblog-cli/internal/syncer"
)

const modulePath = "github.com/nuxtblog/nuxtblog"

// GenerateImports writes server/builtin/plugins.go with blank imports for all plugins.
func GenerateImports(builtinDir string, plugins []syncer.PluginInfo) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by nuxtblog-cli; DO NOT EDIT.\n\n")
	buf.WriteString("package builtin\n\nimport (\n")
	for _, p := range plugins {
		fmt.Fprintf(&buf, "\t_ \"%s/builtin/%s\"\n", modulePath, p.PkgName)
	}
	buf.WriteString(")\n")

	return os.WriteFile(filepath.Join(builtinDir, "plugins.go"), []byte(buf.String()), 0o644)
}
